---
- name: Sucky playbook
  hosts: planetexpress:!farnsworth
  connection: ssh
  gather_facts: yes

  tasks:
      - name: you still suck
        apt:
            name: figlet
            state: absent
  become: yes
